### ISSUE TITLE
Issue in heroku 

### ISSUE THREAD

**Issue by Mdhzair** [BlackAmda/QueenAmdi-Installer-v4#7]
The engine "node" is incompatible with this module. Expected version "^10.0.0 || ^12.0.0 || ^14.0.0 || >=16.0.0". Got "15.2.0"

**Comment by BlackAmda** [comment]
🔧 **Fixed from** [Commit 961aff8ae98cf2e1680459fda2548b8f8f331be7](https://github.com/BlackAmda/QueenAmdi/commit/961aff8ae98cf2e1680459fda2548b8f8f331be7)
